- type: job
  id: ArmyGeneral
  name: Генерал Армии
  description: Ваша задача следить за армией.
  playTimeTracker: JobArmyArmyGeneral
  requirements:
    - !type:RoleTimeRequirement
      role: JobLieutenant
      time: 36000 # Corvax-RoleTime
    - !type:DepartmentTimeRequirement
      department: Army
      time: 108000 # Corvax-RoleTime
#    - !type:OverallPlaytimeRequirement
#      time: 108000
  weight: 10
  icon: "ArmyGeneral"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - ArmyGeneral
  - Army
  - Lieutenant

- type: startingGear
  id: ArmyGeneralGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoS
    back: ClothingMilitaryBackpack
    shoes: ClothingShoesBootsJackSec # Corvax-Resprite
    outerClothing: ClothingOuterCoatHoSTrench
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadHatBeretHoS
    id: ArmyArmy_GeneralPDA
    gloves: ClothingHandsGlovesCombat
    ears: ClothingHeadsetAltSecurity
    belt: ClothingBeltSecurityFilled
  innerclothingskirt: ClothingUniformJumpskirtHoS
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingMilitaryBackpackDuffelMilitary