- type: job
  id: Corporal
  name: Ефрейтор
  description: Служите, помогайте рядовым и никакой дедовщины....
  playTimeTracker: JobArmyCorporal
  requirements:
    - !type:RoleTimeRequirement
        role: JobPrivate
        time: 12000 # Corvax-RoleTime
    - !type:OverallPlaytimeRequirement # Corvax-RoleTime
        time: 12000
        inverted: false # stop playing intern if you're good at security!
  icon: "Corporal"
  supervisors: job-supervisors-security
  canBeAntag: false
  access:
  - Army

- type: startingGear
  id: CorporalGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoS
    back: ClothingMilitaryBackpack
    shoes: ClothingShoesBootsJackSec # Corvax-Resprite
    outerClothing: ClothingOuterCoatHoSTrench
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadHatBeretHoS
    id: ArmyCorpoalPDA
    gloves: ClothingHandsGlovesCombat
    ears: ClothingHeadsetAltSecurity
    belt: ClothingBeltSecurityFilled
  innerclothingskirt: ClothingUniformJumpskirtHoS
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingMilitaryBackpackDuffelMilitary